// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDW-JBd3u5xga8E7kXkQKa1Cb6YHLUp7k8',
    appId: '1:257848485241:web:d97f3ee75a77c970afbba8',
    messagingSenderId: '257848485241',
    projectId: 'quizz-app-6b282',
    authDomain: 'quizz-app-6b282.firebaseapp.com',
    storageBucket: 'quizz-app-6b282.appspot.com',
    measurementId: 'G-DGZP5VS61K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC29eGKwKLB__BVt29TGmItBqX8NrYPcwY',
    appId: '1:257848485241:android:53bedf2adbe615fcafbba8',
    messagingSenderId: '257848485241',
    projectId: 'quizz-app-6b282',
    storageBucket: 'quizz-app-6b282.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDGmAPDer0DqmM8P3jI1zNnSV4iqI_9Lyo',
    appId: '1:257848485241:ios:5ecf84b8d02510c3afbba8',
    messagingSenderId: '257848485241',
    projectId: 'quizz-app-6b282',
    storageBucket: 'quizz-app-6b282.appspot.com',
    androidClientId: '257848485241-hejg3b0r2skdijbqehvojt3g98atod3f.apps.googleusercontent.com',
    iosClientId: '257848485241-ti6v64tphh245ro6n1rpmetb144doicm.apps.googleusercontent.com',
    iosBundleId: 'io.fireship.quizapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDGmAPDer0DqmM8P3jI1zNnSV4iqI_9Lyo',
    appId: '1:257848485241:ios:5ecf84b8d02510c3afbba8',
    messagingSenderId: '257848485241',
    projectId: 'quizz-app-6b282',
    storageBucket: 'quizz-app-6b282.appspot.com',
    androidClientId: '257848485241-hejg3b0r2skdijbqehvojt3g98atod3f.apps.googleusercontent.com',
    iosClientId: '257848485241-ti6v64tphh245ro6n1rpmetb144doicm.apps.googleusercontent.com',
    iosBundleId: 'io.fireship.quizapp',
  );
}
